version: '2'

services:
  freshrss:
    image: freshrss/freshrss:latest
    restart: always
    ports:
      - 80:80
    networks:
      - web
      - default
    volumes:
      - '/root/rssreader:/var/www/FreshRSS/data'
    environment:
      - CRON_MIN=*/5

networks:
  web:
    external: true