version: rav1e-windows-{build}
branches:
  only:
  - master
image: Visual Studio 2017
environment:
  channel: stable
  target: x86_64-pc-windows-msvc
install:
- cmd: >-
    call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"

    appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe

    appveyor DownloadFile https://people.xiph.org/~tdaede/nasm-2.14.02-win64.zip -FileName nasm.zip

    7z e -y nasm.zip

    rustup-init -yv --default-toolchain %channel% --default-host %target%

    set PATH=%PATH%;%USERPROFILE%\.cargo\bin;%APPVEYOR_BUILD_FOLDER%

    rustc -vV

    cargo -vV
build_script:
- cmd: >-
    git submodule update --init

    cargo build --release

    cd target\release

    mkdir buildfinish

    move rav1e.exe buildfinish\

    cd buildfinish

    echo %date% %time% > BuildTime.txt
test: off
artifacts:
- path: target\release\buildfinish
  name: rav1e-windows-x64
  type: WebDeployPackage