% 计算离散时间傅里叶变换的频率样本
clc;
clear;
D = 5;
h_sig = [1, 2, 3, 4, 5, 6, 7, 8, 9];
h_sig_2 = [zeros(1, D), h_sig];
w=0: 0.005: pi;
h = fft(h_sig, size(w, 2));
h_2 = fft(h_sig_2, size(w, 2));
figure(1);
subplot(2, 1, 1);
plot(2 * w / pi, abs(h));
axis([0, 1, -30, 50]);
grid;
title('未延时幅度谱');
xlabel('$$ \omega / \pi $$', 'Interpreter', 'LaTeX');
ylabel('振幅');
subplot(2, 1, 2);
plot(2 * w / pi, angle(h));
axis([0, 1, -10, 10]);
grid;
title('未延时相位谱');
xlabel('$$ \omega / \pi $$', 'Interpreter', 'LaTeX');
ylabel('以弧度为单位的相位');
figure(2);
subplot(2, 1, 1);
plot(2 * w / pi, abs(h_2));
axis([0, 1, -30, 50]);
grid;
title('延时幅度谱');
xlabel('$$ \omega / \pi $$', 'Interpreter', 'LaTeX');
ylabel('振幅');
subplot(2, 1, 2);
plot(2 * w / pi, angle(h_2));
axis([0, 1, -10, 10]);
grid;
title('延时相位谱');
xlabel('$$ \omega / \pi $$', 'Interpreter', 'LaTeX');
ylabel('以弧度为单位的相位');
d_abs = abs(h) - abs(h_2);
d_angle = angle(h) - angle(h_2);
figure(3);
subplot(2, 1, 1);
plot(2 * w / pi, d_abs);
axis([0, 1, -30, 50]);
grid;
title('幅度谱差值');
xlabel('$$ \omega / \pi $$', 'Interpreter', 'LaTeX');
ylabel('振幅');
subplot(2, 1, 2);
plot(2 * w / pi, d_angle);
axis([0, 1, -10, 10]);
grid;
title('相位谱差值');
xlabel('$$ \omega / \pi $$', 'Interpreter', 'LaTeX');
ylabel('以弧度为单位的相位');
